# Generated by Django 5.1.1 on 2024-10-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_no', models.CharField(max_length=255)),
                ('material_name', models.CharField(max_length=255)),
                ('movemenet_type', models.PositiveIntegerField()),
                ('Centre', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('unit_of_entry', models.CharField(max_length=255)),
                ('plant_no', models.CharField(max_length=255)),
                ('receiving_storage_location', models.CharField(max_length=255)),
            ],
        ),
    ]
