# Generated by Django 5.1.1 on 2024-10-05 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_components_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='components',
            old_name='movemenet_type',
            new_name='movement_type',
        ),
    ]
