# Generated by Django 5.1.1 on 2024-10-05 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_movemenet_type_components_movement_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='components',
            old_name='Centre',
            new_name='centre',
        ),
    ]
